=== slawek209343/ZMP/z2/zalazek_3D/grammar/scene.xsd
<?xml version="1.0" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

 <xs:complexType name="Type4Parameter">
   <xs:sequence>
    </xs:sequence>
    <xs:attribute name="Name" type="xs:string" />
    <xs:attribute name="Value" type="xs:float" />
 </xs:complexType>

 <xs:complexType name="Type4Obstacle">
   <xs:sequence>
     <xs:element name="Parameter" type="Type4Parameter"
                                    minOccurs="6" maxOccurs="6"/>
    </xs:sequence>
    <xs:attribute name="Name" type="xs:string" />
 </xs:complexType>


 <xs:complexType name="Type4Scene">
   <xs:sequence>
    <xs:element name="Obstacle" type="Type4Obstacle" minOccurs="0" maxOccurs="unbounded" />
   </xs:sequence>
 </xs:complexType>

 <xs:element name="Scene" type="Type4Scene">
 </xs:element>

</xs:schema>

=== slawek209343/ZMP/z2/zalazek_3D/scene.xml
<Scene xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:noNamespaceSchemaLocation='grammar/scene.xsd' >
    <Obstacle Name="Cuboid_A">
      <Parameter  Name="Center_x" Value="100"/>
      <Parameter  Name="Center_y" Value="15"/>
      <Parameter  Name="Center_z" Value="4"/>
      <Parameter  Name="Size_x" Value="30"/>
      <Parameter  Name="Size_y" Value="80"/>
      <Parameter  Name="Size_z" Value="30"/>
    </Obstacle>
    <Obstacle Name="Cuboid_B">
      <Parameter  Name="Center_x" Value="10"/>
      <Parameter  Name="Center_y" Value="5"/>
      <Parameter  Name="Center_z" Value="0"/>
      <Parameter  Name="Size_x" Value="5"/>
      <Parameter  Name="Size_y" Value="24"/>
      <Parameter  Name="Size_z" Value="18"/>
    </Obstacle>
</Scene>
